myApp/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from . import db
from .models import User
from flask_login import current_user, login_required, login_user, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash


auth = Blueprint("auth", __name__)

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        username = request.form.get("inputUserName3")
        email = request.form.get("inputEmail3")
        password = request.form.get("inputPassword3")
        confirm_password = request.form.get("inputConfirmPassword3")

        user_email_exists = User.query.filter_by(email=email).first()
        user_username_exists = User.query.filter_by(username=username).first()

        if user_email_exists:
            flash('Email is taken.', category='error')
        elif user_username_exists:
            flash('Username is taken.', category='error')
        elif password != confirm_password:
            flash('Passwords do not match!', category='error')
        elif len(username) < 3:
            flash('Username is too short!', category='error')
        elif len(password) < 5 or len(confirm_password) < 5:
            flash('Password is too short!', category='error')
        else:
            try:
                password_hash = generate_password_hash(password)
                new_user = User(username=username, email=email, password=password_hash)
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user, remember=True)
                flash('User account created successfully. You can now access your account', category='success')
                return redirect(url_for('views.home'))
            except Exception as e:
                db.session.rollback()
                flash(f'An error occurred: {str(e)}', category='error')

    return render_template("register.html", title="REGISTER")

@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("inputEmail3")
        password = request.form.get("inputPassword3")

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password.', category='error')
        else:
            flash('Email not found. Please register first.', category='error')

    return render_template("login.html", title="LOGIN")  


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash('Logged out successfully.', category='warning')
    return redirect(url_for("auth.login"))

myApp/views.py
from flask import Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from . import db
import os
from .models import Stories, User, Comments

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

views = Blueprint("views", __name__)
#
@views.route("/")
@views.route("/home")
def home():
    my_stories_data = Stories.query.all()
    return render_template("home.html", title="HOME", stories_data=my_stories_data)

#########storie and actions
@views.route("/create-storie", methods=['GET', 'POST'])
@login_required
def create_story():
    if request.method == 'POST':
        title = request.form.get('title')
        category = request.form.get('category')
        content = request.form.get('content')
        image = request.files.get('image')

        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image.save(image_path)

            new_story = Stories(
                title=title,
                image=filename,
                category=category,
                content=content,
                author=current_user.id
            )
            db.session.add(new_story)
            db.session.commit()

            flash('Your story has been created!', 'success')
            return redirect(url_for('views.home'))
        else:
            flash('New Storie created but no file uploaded', 'succes')
            new_story = Stories(
                title=title,
                image='',
                category=category,
                content=content,
                author=current_user.id
            )
            db.session.add(new_story)
            db.session.commit()

    return render_template("create_storie.html", title="NEW")
#
@views.route("/edit-storie/<id>", methods=['GET', 'POST'])
@login_required
def edit_storie(id):
    # Fetches the current stories and populates to be changed in the form
    existing_storie = Stories.query.filter_by(id=id).first()
    if not existing_storie:
        flash('Story not found', 'danger')
        return redirect(url_for('views.home'))
    
    if existing_storie.author != current_user.id:
        flash('You are not authorized to edit this story.', 'danger')
        return redirect(url_for('views.home'))

    # Fetches form data to be updated
    if request.method == 'POST':
        title = request.form.get('title')
        category = request.form.get('category')
        content = request.form.get('content')

        # Update the story fields
        existing_storie.title = title
        existing_storie.category = category
        existing_storie.content = content

        if 'image' in request.files and request.files['image'].filename != '':
            image_file = request.files.get('image')
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image_file.save(image_path)
            existing_storie.image = filename

        # Save the changes to the database
        db.session.commit()

        flash('Story updated successfully!', 'success')
        return redirect(url_for('views.home'))

    return render_template("edit_storie.html", title='edit', current_storie=existing_storie)
#
@views.route("/delete-storie/<id>")
@login_required
def delete_storie(id):
    storie = Stories.query.filter_by(id=id).first()

    if not storie:
        flash("Error while trying to delete, check if the storie existx.", category="error")
    elif storie.author != current_user.id:
        flash("You do not have the permission to delete this storie!", category="error")
    else:
        db.session.delete(storie)
        db.session.commit()
        flash("Storie deleted!", category="success")
    
    
    return redirect(url_for('views.home'))
########storie sub actions
@views.route("/view-stories/<username>")
def view_user_stories(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash("User not found!", category="error")
        return redirect(url_for('views.home'))
    
    user_stories = Stories.query.filter_by(author=user.id).all()
    title = f"{user.username}'s Stories"
    
    return render_template("view_user_stories.html", title=title, stories_data=user_stories)
#
@views.route("/view-storie/<id>")
def view_storie(id):
    storie = Stories.query.filter_by(id=id).first()
    if not storie:
        flash("Storie was not found!", category="error")
        return redirect(url_for('views.home'))
    title=storie.title
    return render_template("view_storie.html", title=title, storie=storie)

####storie comment sub actions
@views.route("/create-comment/<storie_id>", methods=[ 'POST'])
@login_required
def create_comment(storie_id):
    coment = request.form.get('coment')
    storie = Stories.query.filter_by(id=storie_id).first()
    
    
    if not coment:
        flash('Error: Your coment cannot be empty', category='error')
    else:    
        if not storie:
            flash("Storie was not found!", category="error")
            return redirect(url_for('views.home'))
        else:
            new_comment = Comments(content=coment, storie=storie_id, author=current_user.id)
            db.session.add(new_comment)
            db.session.commit()
            flash('Your comment has been added!', 'success')
    

    return render_template("view_storie.html", storie=storie)

@views.route('/get-comment')
def get_comment():
    comments_data=Comments.query.all()
    return render_template("view_storie.html", comments_data=comments_data)


@views.route("/delet-comment/<id>")
def delete_comment(id):
    comment_to_delete = Comments.query.filter_by(id=id).first()

    if not comment_to_delete:
        flash('comment does not exist', category='error')
    elif comment_to_delete.author != current_user.id:
        flash("You do not have the permission to delete this comment!", category="error")
    else:
        db.session.delete(comment_to_delete)
        db.session.commit()
        flash("Storie deleted!", category="success")
    

myApp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS link (CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    {% if title %}
    <title>{{ title }} - STORIE</title>
    {% else %}
    <title>Welcome to STORIE</title>
    {% endif %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button
                class="navbar-toggler bg-dark"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar"
                aria-controls="navbar"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="/">STORIE</a>
                    <a class="nav-item nav-link" href="/logout">LOGOUT</a>
                    {% else %}
                    <a class="nav-item nav-link" href="/login">LOGIN</a>
                    <a class="nav-item nav-link" href="/sign-up">SIGN UP</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>  
            {% elif category == 'success'%}
            <div class="alert alert-success alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> 
            {% else %}
            <div class="alert alert-warning alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> 
            {% endif %}  
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Bootstrap JS bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous">
    </script>
</body>
</html>

myApp/templates/create_storie.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="text-left">
            <a class=" text-success" href="/"><-GO TO HOMEPAGE</a>
        </div>
    <h1 class="text-center mb-4">New Story</h1>
    <form method="POST" enctype="multipart/form-data">
        
        <div class="form-group mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="form-group mb-3">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name="image" accept="image/*">
        </div>
        <div class="form-group mb-3">
            <label for="category">Category</label>
            <input type="text" class="form-control" id="category" name="category">
        </div>
        <div class="form-group mb-3">
            <label for="content">Content</label>
            <textarea class="form-control" id="content" name="content" rows="5" required></textarea>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Create Story</button>
        </div>
    </form>
   
</div>
{% endblock %}

myApp/templates/edit_storie.html
{% extends "base.html" %}

{% block content %}
<div class="text-left mb-4 mt-4">
    <a class="text-success" href="/"><-GO TO HOMEPAGE</a>
</div>
<div class="container">
   
    <h1 class="text-center mb-4">Edit Your Story</h1>
    {% if current_storie != '' %}
    <form method="PUT" action="{{ url_for('views.edit_storie', id=current_storie.id) }}" enctype="multipart/form-data">
        <div class="form-group mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ current_storie.title }}" required>
        </div>
        <div class="form-group mb-3">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name="image" accept="image/*">
            {% if current_storie.image %}
            <p class="mt-2">Current image: {{ current_storie.image }}</p>
            {% endif %}
        </div>
        <div class="form-group mb-3">
            <label for="category">Category</label>
            <input type="text" class="form-control" id="category" name="category" value="{{ current_storie.category }}">
        </div>
        <div class="form-group mb-3">
            <label for="content">Content</label>
            <textarea class="form-control" id="content" name="content" rows="5" required>{{ current_storie.content }}</textarea>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Update Story</button>
        </div>
    </form>
    {% endif %}   
</div>
{% endblock %}

myApp/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Hello {{current_user.username}},</h1>
<h2> welcome to STORIE</h2>
<p>STORIE is a platform where you can share your stories with the world.</p>
<p>Click on the link below to start sharing your stories.</p>
<div class="mb-4">
<a href="/create-storie" class="btn btn-primary">CREATE STORIES</a>
<small class="text-muted float-end">
    {% for storie in stories_data %}
    {% if storie.author == current_user.id %}
    <a href="/view-stories/{{ storie.user.username }}">
        My Stories
    </a>
    {% endif %}
    {%endfor%}
</small>
</div>

{% for storie in stories_data %}
<div class="card mb-3 ">
    <a href="/view-storie/{{ storie.id }}">
    <a class="" href="/view-storie/{{storie.id}}">
    {%if storie.image == ''%}
    <img src="https://picsum.photos/1280/720" class="card-img-top" alt="...">
    {%else%}
    <img src="{{storie.image}}" class="card-img-top" alt='{{storie.title}}'>
    {%endif%}
    <div class="card-body">
        <h5 class="card-title">{{storie.title}}</h5>
        <p class="card-text"><small class="text-muted"><a href="/storie/{{storie.category}}">{{storie.category}}</a></small></p>
    </div>
    <div class="card-footer">
        <small class="text-muted
        {% if storie.user_id == current_user.id %}
        float-start
        {% endif %}
        ">
        {% if storie.author == current_user.id %}
        <div class="btn-group">
            <button
            type="button"
            data-bs-toggle="dropdown"
            class="btn btn-sm btn-secondary dropdown-toggle"
            ></button>
            <ul class="dropdown-menu">
                <li><a href="/edit-storie/{{storie.id}}" class="btn btn-primary dropdown-item">Edit</a></li>
                <li><a href="/delete-storie/{{storie.id}}" class="btn btn-danger dropdown-item">Delete</a></li>
            </ul>
        </div>
        {%else%}
        <small >By: <a href="/view-stories/{{storie.user.username}}">{{storie.user.username}}</a></small>
        {% endif %}
        {{storie.created_at}}
        </small>
        
        <small class="text-muted float-end">On: {{storie.date_created}}</small>
        </div>
        </a>
</div>

{%endfor%}
{%endblock%}

myApp/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ user.username }}!</h1>
    {% for post in posts %}
    <div>
      <p>{{ post.author.username }} says: <b>{{ post.body }}</b></p>
    </div>
    {% endfor %}
{% endblock %}

myApp/templates/login.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{{ url_for('auth.login') }}">
    <h1 align="center">LOGIN</h1>
    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Email Address</label>
        <div class="col-sm-10">
            <input type="email" name="inputEmail3" class="form-control" id="inputEmail3" placeholder="Enter Email">
        </div>
    </div>
    <div class="row mb-3">
        <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
            <input type="password" name="inputPassword3" class="form-control" id="inputPassword3" placeholder="Enter password">
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-10 offset-sm-2">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck1">
                <label class="form-check-label" for="gridCheck1">
                    Keep me logged in
                </label>
            </div>
        </div>
    </div>
    <div align="center">
        <button type="submit" class="btn btn-success">LOGIN</button>
    </div>
    <div align="center">
        <p>Don't have an Account? <span><a class="nav-item nav-link" href="/sign-up">REGISTER</a></span></p>
    </div>
</form>
{% endblock %}

myApp/templates/logout.html
{% extends "base.html" %}

{% block content %}
<h1>LoGOuT</h1>

{% endblock %}

myApp/templates/register.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{{ url_for('auth.sign_up') }}">
    <h1 align="center">REGISTER</h1>
    <div class="row mb-3">
        <label for="inputUserName3" class="col-sm-2 col-form-label">User Name</label>
        <div class="col-sm-10">
            <input type="text" name="inputUserName3" class="form-control" id="inputUserName3" placeholder="Enter Username">
        </div>
    </div>
    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Email Address</label>
        <div class="col-sm-10">
            <input type="email" name="inputEmail3" class="form-control" id="inputEmail3" placeholder="Enter Email">
        </div>
    </div>
    <div class="row mb-3">
        <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
            <input type="password" name="inputPassword3" class="form-control" id="inputPassword3" placeholder="Enter password">
        </div>
    </div>
    <div class="row mb-3">
        <label for="inputConfirmPassword3" class="col-sm-2 col-form-label">Confirm password</label>
        <div class="col-sm-10">
            <input type="password" name="inputConfirmPassword3" class="form-control" id="inputConfirmPassword3" placeholder="Confirm password">
        </div>
    </div>
    <div align="center">
        <button type="submit" class="btn btn-success">REGISTER</button>
    </div>
    <div align="center">
        <p>Have an Account? <span><a class="nav-item nav-link" href="/login">LOGIN</a></span></p>
    </div>
</form>
{% endblock %}

myApp/templates/view_storie.html
{% extends "base.html" %}
{% block content %}
<div class="text-left mb-4 mt-4">
    <a class=" text-success" href="/"><-GO TO HOMEPAGE</a>
</div>
<div class="card mb-3">
   
    {% if storie.image == '' %}
    <img src="https://picsum.photos/1280/720" class="card-img-top" alt="...">
    {% else %}
    <img src="{{ storie.image }}" class="card-img-top" alt="{{ storie.title }}">
    {% endif %}
    
    <div class="card-body">
        <h5 class="card-title">{{ storie.title }}</h5>
        <p class="card-text">
            <small class="text-muted">
                <a href="/storie/{{ storie.category }}">{{ storie.category }}</a>
            </small>
        </p>
    </div>
    
    <div class="card-footer">
        <small class="text-muted {% if storie.user_id == current_user.id %}float-start{% endif %}">
            {% if storie.author == current_user.id %}
            <div class="btn-group">
                <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown"></button>
                <ul class="dropdown-menu">
                    <li><a href="/edit-storie/{{ storie.id }}" class="btn btn-primary dropdown-item">Edit</a></li>
                    <li><a href="/delete-storie/{{ storie.id }}" class="btn btn-danger dropdown-item">Delete</a></li>
                </ul>
            </div>
            {% else %}
            <small>By: <a href="/view-stories/{{ storie.user.username }}">{{ storie.user.username }}</a></small>
            {% endif %}
            {{ storie.created_at }}
        </small>
        
        <small class="text-muted float-end">On: {{ storie.date_created }}</small>
    </div>
    
    {% if current_user.is_authenticated %}
    <div class="m-4">
        <h4 align="center">React to post</h2>
        <form method="POST" enctype="multipart/form-data" action="/create-comment/{{storie.id}}">
            <h5>Comment</h4>
           
            <div class="form-group mb-3">
                <label for="coment">Comment</label>
                <textarea class="form-control" id="coment" name="coment" rows="5" placeholder="Add your comment"></textarea>
            </div>
            <div class="text-center float-end">
                <button type="submit" class="btn btn-info">Add Comment</button>
            </div>
        </form>
    </div>
    {% else %}
    <h1 align="center" class="text-warning">
        <span><a class="nav-item nav-link text-success" href="/sign-up">SIGN UP</a></span>
        or
        <span><a class="nav-item nav-link text-success" href="/login">LOGIN</a></span>
        to leave a comment
    </h1>
    {% endif %}
    
    <div>
        <h2 align="center">Comments</h2>
        <div>
            {% for comment in comment_data %}
            {%if comment.image == ''%}
            <div>
            <p>{{comment.content}}</p>
            <small class="text-muted float-end">By {{comment.user.username}}, on {{comment.date_created}}</small>
            </div>
            {%else%}
            <div>
                <p>{{comment.content}}</p>
                <small class="text-muted float-end">By {{comment.user.username}}, on {{comment.date_created}}</small>
                </div>
            {%endif%}
            {%endfor%}
        </div>
    </div>
</div> 

{% endblock %}

myApp/templates/view_story.html
{% extends "base.html" %}

{% block content %}
<h1>Hello {{name}}</h1>

{% endblock %}

myApp/templates/view_user_stories.html
{%extends "base.html"%}
{%block content%}
<div class="text-left mb-4 mt-4"> 
    <a class=" text-success" href="/"><-GO TO HOMEPAGE</a>
</div>
{% if stories_data %}
    {% if stories_data[0].author == current_user.id %}
        <h1 align="center">Hello {{ stories_data[0].user.username }}, welcome to your stories timeline</h1>
    {% else %}
        <h1 align="center">Hello, welcome to stories by {{ stories_data[0].user.username }}</h1>
    {% endif %}
{% endif %}

{% for storie in stories_data %}

<div class="card mb-3">
    <a href="/view-storie/{{ storie.id }}">
    {%if storie.image == ''%}
    <img src="https://picsum.photos/1280/720" class="card-img-top" alt="...">
    {%else%}
    <img src="{{storie.image}}" class="card-img-top" alt='{{storie.title}}'>
    {%endif%}
    <div class="card-body">
        <h5 class="card-title">{{storie.title}}</h5>
        <p class="card-text"><small class="text-muted"><a href="/storie/{{storie.category}}">{{storie.category}}</a></small></p>
    </div>
    <div class="card-footer">
        <small class="text-muted
        {% if storie.user_id == current_user.id %}
        float-start
        {% endif %}
        ">
        {% if storie.author == current_user.id %}
        <div class="btn-group">
            <button
            type="button"
            data-bs-toggle="dropdown"
            class="btn btn-sm btn-secondary dropdown-toggle"
            ></button>
            <ul class="dropdown-menu">
                <li><a href="/edit-storie/{{storie.id}}" class="btn btn-primary dropdown-item">Edit</a></li>
                <li><a href="/delete-storie/{{storie.id}}" class="btn btn-danger dropdown-item">Delete</a></li>
            </ul>
        </div>
        {%else%}
        <small >By: <a href="/stories/{{storie.username}}">{{storie.user.username}}</a></small>
        {% endif %}
        {{storie.created_at}}
        </small>
        
        <small class="text-muted float-end">On: {{storie.date_created}}</small>
        </div>
    </a>
</div>

{%endfor%}
{%endblock%}